repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--diff"
          - "--line-length=99"
          - "--multi-line=0"
          - "--force-grid-wrap=0"
          - "--lines-between-types=0"
          - "--lines-before-imports=0"
          - "--no-lines-before=STDLIB,THIRDPARTY,FIRSTPARTY"
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=99", "--ignore=E203,W503"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: ^sbigw/config/.*\.ya?ml$
