name: Clean Old Documentation

on:
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Clean old UML diagrams
      run: |
        # Remove UML diagrams older than 30 days
        find docs/api/uml -name "*.png" -mtime +30 -delete 2>/dev/null || true
    
    - name: Commit cleanup
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git diff --staged --quiet || git commit -m "Clean old documentation files [skip ci]"
        git push || true

